### ISSUE TITLE
USER STORY: Manage genres

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/the_paper_lounge#13]
As a **site admin** I can **manage genres** so that **I can add to, modify or remove them**

## Acceptance Criteria

* Admin user will be able to view the genres from the admin page
* Admin user can then edit the genres as required
  
## Tasks
  
 - [ ] Configure the admin view accordingly
 - [ ] Configure any required templates as needed
 - [ ]  Update the admin URL if required to allow this
