### ISSUE TITLE
USER STORY: Remove users

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/the_paper_lounge#14]
As a **site admin** I can **remove users** so that **they will no longer be able to post unsuitable content**

## Acceptance Criteria

* Admin user will be able to view user accounts under the admin view
* Users can be removed 
  
## Tasks
  
 - [ ]  Update the admin view to allowing view of user accounts
 - [ ] Update any required templates
 - [ ] Make any required changes to the admin URL
