### ISSUE TITLE
USER STORY: Access admin panel from nav bar

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/the_paper_lounge#18]
As an **admin** I can **access the admin panel from the navigation when logged in** so that **I don't have to manually type the URL each time**

## Acceptance Criteria

* When logged in, the admin can see a link in the navigation which when clicked takes them to the admin panel.
  
## Tasks
  
 - [ ] Add link to nav bar
 - [ ] Ensure only visible when admin is logged in
 - [ ] Ensure 'Contact Us' link is in place of 'Admin Panel' link when any other user is logged in
