### ISSUE TITLE
USER STORY: View genres 

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/the_paper_lounge#2]
As a **site user** I can **view and click on different genre categories** so that **I can find reviews relevant to my specific reading interests**

## Acceptance Criteria

* User is able to view available genres from the home page via a dropdown menu
* User is able to see related reviews if a genre is selected
  
## Tasks
  
 - [x]  Configure the required view
 - [x] Configure the required templates
 - [x]  Configure the required URL
