### ISSUE TITLE
USER STORY: Sign up 

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/the_paper_lounge#3]
As a **site user** I can **register for an account** to **be able to post reviews and comments**

## Acceptance Criteria

* The user is able to click on a link to register an account
* The user will be presented with a form to complete to set up a new account
  
## Tasks
  
 - [x]  Install the All-Auth module
 - [x] Configure the required view
 - [x]  Configure the required template
 - [x]  Configure the required URL
 - [x] User is given feedback to let them know they are successfully logged in after submitting register form
