### ISSUE TITLE
USER STORY: Like/Unlike a review

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/the_paper_lounge#6]
As a **site user** I can **like or unlike a review** so that **I can interact with the content**

## Acceptance Criteria

* An authenticated user will be able to like/unlike a comment when viewing a review in detail
*  There will be a likes section where number of likes and like option will display
  
## Tasks
  
 - [ ]  Update the Review Detail view to allow likes
  - [ ] Update the Review Detail template
  - [ ] Configure any required URLs to allow this functionality
