### ISSUE TITLE
USER STORY: Contact form

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/the_paper_lounge#7]
As a **site user** I can **fill out and submit a contact form** so that **I can make admin aware of any issues or feedback**

## Acceptance Criteria

* User will be able to navigate to, fill out and submit a contact form
  
## Tasks
  
- [x] Install 'contact us' app
- [x] Create Contact model
- [x] Create Form
 - [x] Configure the required view
 - [x]  Configure the required template
 - [x]  Configure the required URLs
